repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use a recent stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: mixed-line-ending
      - id: detect-private-key
  
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2 # Replace with the desired Ruff version
    hooks:
      - id: ruff-format
        # Run the ruff formatter on all files
      - id: ruff-check
        args: [ --fix ] # Automatically fix linting errors where possible